Publicación automática con GitHub Pages
`yaml
name: Despliegue automático
on: push
jobs:
deploy:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v3
- uses: actions/configure-pages@v3
- uses: actions/upload-pages-artifact@v2
with:
path: ./
- uses: actions/deploy-pages@v2
